<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.kinlhp</groupId>
		<artifactId>moname-commons</artifactId>
		<version>${revision}</version>
	</parent>
	<artifactId>moname-commons-stream</artifactId>
	<name>${project.artifactId}</name>
	<description>Project to money me with no name [commons-stream].</description>
	<properties>
		<main.basedir>${basedir}/../..</main.basedir>
	</properties>
	<dependencies>
		<!-- # third party # -->
		<!-- jakarta -->
		<dependency>
			<!-- README#jsr-380 -->
			<groupId>jakarta.annotation</groupId>
			<artifactId>jakarta.annotation-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<!-- slf4j -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<scope>provided</scope>
		</dependency>
	</dependencies>
	<profiles>
		<profile>
			<id>test</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<build>
				<plugins>
					<!-- # third party # -->
					<!-- gmavenplus -->
					<plugin>
						<groupId>org.codehaus.gmavenplus</groupId>
						<artifactId>gmavenplus-plugin</artifactId>
					</plugin>
					<!-- jacoco -->
					<plugin>
						<groupId>org.jacoco</groupId>
						<artifactId>jacoco-maven-plugin</artifactId>
					</plugin>
					<!-- maven -->
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
					</plugin>
				</plugins>
			</build>
			<dependencies>
				<!-- # third party # -->
				<!-- junit -->
				<dependency>
					<groupId>org.junit.jupiter</groupId>
					<artifactId>junit-jupiter-api</artifactId>
					<scope>test</scope>
				</dependency>
				<!-- slf4j -->
				<dependency>
					<!--
					SLF4J(W): No SLF4J providers were found.
					SLF4J(W): Defaulting to no-operation (NOP) logger implementation
					SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
					-->
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-nop</artifactId>
					<scope>test</scope>
				</dependency>
			</dependencies>
		</profile>
	</profiles>
</project>
