com.kinlhp.moname.commons.test.testcontainers.autoconfigure.keycloak.KeycloakAutoConfiguration
com.kinlhp.moname.commons.test.testcontainers.autoconfigure.keycloak.KeycloakAutoConfiguration.ConditionalOnClass=dasniko.testcontainers.keycloak.ExtendableKeycloakContainer
