package com.kinlhp.moname.commons.jpa.id.ulid;

import java.io.Serial;
import java.lang.reflect.Member;
import java.util.EnumSet;
import java.util.UUID;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;

import com.github.f4b6a3.ulid.Ulid;
import org.hibernate.HibernateException;
import org.hibernate.Internal;
import org.hibernate.MappingException;
import org.hibernate.engine.spi.SharedSessionContractImplementor;
import org.hibernate.generator.BeforeExecutionGenerator;
import org.hibernate.generator.EventType;
import org.hibernate.generator.GeneratorCreationContext;
import org.hibernate.id.factory.spi.CustomIdGeneratorCreationContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.kinlhp.moname.commons.jpa.type.descriptor.java.UlidJavaType;
import com.kinlhp.moname.commons.jpa.type.descriptor.java.UlidJavaType.ValueTransformer;

import static com.kinlhp.moname.commons.jpa.annotations.UlidGenerator.Style.AUTO;
import static org.hibernate.generator.EventTypeSets.INSERT_ONLY;
import static org.hibernate.internal.util.ReflectHelper.getPropertyType;

/**
 * @see org.hibernate.id.uuid.UuidGenerator UuidGenerator
 */
public class UlidGenerator implements BeforeExecutionGenerator {

	@Serial
	private static final long serialVersionUID = -2976405095128318167L;

	@Nonnull
	private static final Logger LOG = LoggerFactory.getLogger(UlidGenerator.class);

	@Nonnull
	@SuppressWarnings("java:S1948")
	private final UlidValueGenerator generator;

	@Nonnull
	@SuppressWarnings("java:S1948")
	private final ValueTransformer valueTransformer;

	/**
	 * This form is used when there is no {@link com.kinlhp.moname.commons.jpa.annotations.UlidGenerator UlidGenerator}
	 * but we know we want this generator
	 */
	@Internal
	public UlidGenerator(@Nonnull final Class<?> memberType) {
		generator = MonotonicUlidStrategy.getSingleton();
		valueTransformer = determineValueTransformer(memberType);
	}

	public UlidGenerator(@Nonnull final com.kinlhp.moname.commons.jpa.annotations.UlidGenerator config,
			@Nonnull final Member idMember,
			@Nonnull @SuppressWarnings({"unused", "java:S1172"}) final CustomIdGeneratorCreationContext creationContext) {
		this(config, idMember);
	}

	public UlidGenerator(@Nonnull final com.kinlhp.moname.commons.jpa.annotations.UlidGenerator config,
			@Nonnull final Member member,
			@Nonnull @SuppressWarnings({"unused", "java:S1172"}) final GeneratorCreationContext creationContext) {
		this(config, member);
	}

	private UlidGenerator(@Nonnull final com.kinlhp.moname.commons.jpa.annotations.UlidGenerator config,
			@Nonnull final Member member) {
		generator = determineValueGenerator(config, member);
		valueTransformer = determineValueTransformer(member);
	}

	@Nonnull
	private UlidValueGenerator determineValueGenerator(
			@Nonnull final com.kinlhp.moname.commons.jpa.annotations.UlidGenerator config,
			@Nonnull final Member member) {
		return !UlidValueGenerator.class.equals(config.algorithm())
				? determineCustomValueGenerator(config, member)
				: determineDefaultValueGenerator(config, member);
	}

	@Nonnull
	private UlidValueGenerator determineCustomValueGenerator(
			@Nonnull final com.kinlhp.moname.commons.jpa.annotations.UlidGenerator config,
			@Nonnull final Member member) {
		if (!AUTO.equals(config.style())) {
			@Nonnull final var message = """
					Style [%s] should not be specified with custom ULID value generator : %s.%s (just style AUTO is \
					allowed)"""
					.formatted(config.style().name(), member.getDeclaringClass().getName(), member.getName());
			LOG.error(message);
			throw new MappingException(message);
		}
		return instantiateCustomGenerator(config.algorithm());
	}

	@Nonnull
	private static UlidValueGenerator instantiateCustomGenerator(
			@Nonnull final Class<? extends UlidValueGenerator> algorithmClass) {
		try {
			LOG.trace("A ULID will be generated by the custom value generation implementation {}",
					algorithmClass.getName());
			return algorithmClass.getDeclaredConstructor().newInstance();
		} catch (@Nonnull @SuppressWarnings("java:S2139") final Exception exception) {
			@Nonnull final var message = "Unable to instantiate %s".formatted(algorithmClass.getName());
			LOG.error(message, exception);
			throw new HibernateException(message, exception);
		}
	}

	@Nonnull
	private UlidValueGenerator determineDefaultValueGenerator(
			@Nonnull final com.kinlhp.moname.commons.jpa.annotations.UlidGenerator config,
			@Nonnull final Member member) {
		@Nonnull final var message = "A {}ULID will be generated for member '%s'".formatted(member);
		return switch (config.style()) {
			case HASH -> {
				checkHashStyle(config, member);
				LOG.trace(message, "Hash ");
				yield HashUlidStrategy.getSingleton();
			}
			case ULID -> {
				LOG.trace(message, "");
				yield UlidStrategy.getSingleton();
			}
			default -> {
				LOG.trace(message, "Monotonic ");
				yield MonotonicUlidStrategy.getSingleton();
			}
		};
	}

	private void checkHashStyle(
			@Nonnull final com.kinlhp.moname.commons.jpa.annotations.UlidGenerator config,
			@Nonnull final Member member) {
		@Nonnull final Class<?> type = member.getDeclaringClass();
		if (!HashableUlid.class.isAssignableFrom(type)) {
			@Nonnull final var exceptionMessage =
					"[%s] style requires that the member it is present in be an implementation of %s, and %s is not"
							.formatted(config.style().name(), HashableUlid.class.getName(), type.getName());
			LOG.error(exceptionMessage);
			throw new MappingException(exceptionMessage);
		}
	}

	@Nonnull
	private ValueTransformer determineValueTransformer(@Nonnull final Class<?> memberType) {
		@Nonnull final var message = "Defining {} value transformer for member type {}";
		return switch (memberType) {
			case @Nonnull final Class<?> type when Ulid.class.isAssignableFrom(type) -> {
				LOG.trace(message, "ULID", type.getName());
				yield UlidJavaType.PassThroughTransformer.getSingleton();
			}
			case @Nonnull final Class<?> type when UUID.class.isAssignableFrom(type) -> {
				LOG.trace(message, "UUID", type.getName());
				yield UlidJavaType.ToUuidTransformer.getSingleton();
			}
			case @Nonnull final Class<?> type when String.class.isAssignableFrom(type) -> {
				LOG.trace(message, "string", type.getName());
				yield UlidJavaType.ToStringTransformer.getSingleton();
			}
			case @Nonnull final Class<?> type when byte[].class.isAssignableFrom(type) -> {
				LOG.trace(message, "byte array", type.getName());
				yield UlidJavaType.ToBytesTransformer.getSingleton();
			}
			default -> {
				LOG.error("Only ULID, UUID, string and byte array types are supported");
				throw new HibernateException("Unanticipated return type [%s] for ULID conversion"
						.formatted(memberType.getName()));
			}
		};
	}

	@Nonnull
	private ValueTransformer determineValueTransformer(@Nonnull final Member member) {
		LOG.trace("Defining value transformer for member {}", member.getName());
		return determineValueTransformer(getPropertyType(member));
	}

	@Nonnull
	@Override
	public EnumSet<EventType> getEventTypes() {
		return INSERT_ONLY;
	}

	@Nonnull
	@Override
	public Object generate(@Nonnull final SharedSessionContractImplementor session, @Nonnull final Object owner,
			@Nullable final Object currentValue, @Nonnull final EventType eventType) {
		@Nonnull final var generatedValue = switch (owner) {
			case @Nonnull final HashableUlid hashableUlid -> {
				LOG.trace("Generating a hashable ULID");
				yield generateHashUlid(session, hashableUlid);
			}
			default -> {
				LOG.trace("Generating a non-hashable ULID");
				yield generator.generateUlid(session);
			}
		};
		return valueTransformer.transform(generatedValue);
	}

	@Nonnull
	private Ulid generateHashUlid(@Nonnull final SharedSessionContractImplementor session,
			@Nonnull final HashableUlid hashableUlid) {
		return ((generator instanceof @Nonnull final HashUlidStrategy hashUlidStrategy)
				&& hashableUlid.getHashConfig().isPresent())
				? hashUlidStrategy.generateUlid(session, hashableUlid.getHashConfig().get())
				: generator.generateUlid(session);
	}
}
