# https://github.com/compose-spec/compose-spec/blob/main/schema/compose-spec.json
services:
  keycloak:
    build:
      context: .
      dockerfile: Containerfile
      args:
        keycloakImage: ${KEYCLOAK_IMAGE:?unset or empty in the .env file}
        KC_DB: ${KEYCLOAK_DATABASE_VENDOR:?unset or empty in the .env file}
        KC_DB_PASSWORD: ${MONAME}
        #KC_DB_URL: "jdbc:${KEYCLOAK_DATABASE_VENDOR:?unset or empty in the .env file}://${MYSQL_NAME}:${MYSQL_PORT}/${KEYCLOAK_NAME}_test\
        #  ?cachePrepStmts=true\
        #  &cacheResultSetMetadata=true\
        #  &cacheServerConfiguration=true\
        #  &characterEncoding=UTF-8\
        #  &connectionCollation=utf8mb4_general_ci\
        #  &connectionTimeZone=UTC\
        #  &createDatabaseIfNotExist=true\
        #  &elideSetAutoCommits=true\
        #  &maintainTimeStats=false\
        #  &prepStmtCacheSize=256\
        #  &prepStmtCacheSqlLimit=2048\
        #  &rewriteBatchedStatements=true\
        #  &useLocalSessionState=true\
        #  &useServerPrepStmts=true"
        KC_DB_URL_DATABASE: ${KEYCLOAK_NAME}_test
        KC_DB_URL_HOST: ${MYSQL_NAME}
        KC_DB_URL_PORT: ${MYSQL_PORT}
        KC_DB_URL_PROPERTIES: "?cachePrepStmts=true\
          &cacheResultSetMetadata=true\
          &cacheServerConfiguration=true\
          &characterEncoding=UTF-8\
          &connectionCollation=utf8mb4_general_ci\
          &connectionTimeZone=UTC\
          &createDatabaseIfNotExist=true\
          &elideSetAutoCommits=true\
          &maintainTimeStats=false\
          &prepStmtCacheSize=256\
          &prepStmtCacheSqlLimit=2048\
          &rewriteBatchedStatements=true\
          &useLocalSessionState=true\
          &useServerPrepStmts=true"
        KC_DB_USERNAME: ${KEYCLOAK_NAME}
        KC_FEATURES: hostname:v2,token-exchange:v1
        KC_HEALTH_ENABLED: true
        KC_HOSTNAME: ${KEYCLOAK_NAME}
        KC_HTTP_MANAGEMENT_RELATIVE_PATH: /management
        KC_HTTP_RELATIVE_PATH: /auth
        KC_HTTPS_KEY_STORE_FILE: /opt/${KEYCLOAK_NAME}/conf/keystore.ed25519.p12
        #KC_HTTPS_KEY_STORE_FILE: /opt/${KEYCLOAK_NAME}/conf/keystore.rsa.p12
        KC_HTTPS_KEY_STORE_PASSWORD: ${MONAME}
        KC_HTTPS_PROTOCOLS: TLSv1.3
        KC_METRICS_ENABLED: true
      additional_contexts:
        keycloak: ../../../${MONAME}-commons/${MONAME}-commons-test/src/main/resources/oidc/${KEYCLOAK_NAME}
    command: ${KEYCLOAK_COMMAND:?unset or empty in the .env file}
    container_name: ${KEYCLOAK_NAME}
    depends_on:
      mysql:
        condition: service_healthy
        required: true
        restart: true
    env_file:
      - .env
    expose:
      - ${KEYCLOAK_HTTP_MANAGEMENT_PORT:?unset or empty in the .env file}
      - ${KEYCLOAK_HTTPS_PORT:?unset or empty in the .env file}
    healthcheck:
      disable: false
      interval: 5s
      retries: 6
      test: [
        'CMD-SHELL',
        '${KEYCLOAK_HEALTHCHECK:?unset or empty in the .env file}'
      ]
      timeout: 3s
      #start_period:
      #start_interval:
    hostname: ${KEYCLOAK_NAME}
    image: ${KEYCLOAK_IMAGE}-optimized
    networks:
      - ${MONAME}
    ports:
      - ${KEYCLOAK_HTTPS_PORT}:${KEYCLOAK_HTTPS_PORT}
      - ${KEYCLOAK_HTTP_MANAGEMENT_PORT}:${KEYCLOAK_HTTP_MANAGEMENT_PORT}
    restart: ${RESTART_POLICY:?unset or empty in the .env file}
    volumes:
      #- ${HOME:?unset or empty in the .env file}/.docker/volumes/${KEYCLOAK_NAME}-data:/opt/${KEYCLOAK_NAME}
      - type: volume
        source: ${KEYCLOAK_NAME}-data
        target: /opt/${KEYCLOAK_NAME}
volumes:
  keycloak-data:
    name: ${KEYCLOAK_NAME}-data
    labels:
      spring.security.oauth2.client.provider: ${KEYCLOAK_NAME}
