CREATE SCHEMA IF NOT EXISTS `keycloak_test` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
CREATE USER IF NOT EXISTS 'keycloak'@'%' IDENTIFIED BY 'moname';
GRANT ALL PRIVILEGES ON TABLE `keycloak_test`.* TO 'keycloak'@'%';
FLUSH PRIVILEGES;
