# https://github.com/compose-spec/compose-spec/blob/main/schema/compose-spec.json
services:
  sqlserver:
    #env_file:
      #- sqlserver/.env
    image: ${SQLSERVER_IMAGE:?unset or empty in the .env file}
    container_name: ${SQLSERVER_NAME:?unset or empty in the .env file}
    volumes:
      #- ../../../moname-commons/moname-commons-test/src/main/resources/db/sqlserver/initial-command.sh:/home/mssql/initial-command.sh
      - type: bind
        source: ../../../moname-commons/moname-commons-test/src/main/resources/db/sqlserver/initial-command.sh
        target: /home/mssql/initial-command.sh
        read_only: true
      #- ../../../moname-commons/moname-commons-test/src/main/resources/db/sqlserver/initial-setup.sql:/home/mssql/initial-setup.sql
      - type: bind
        source: ../../../moname-commons/moname-commons-test/src/main/resources/db/sqlserver/initial-setup.sql
        target: /home/mssql/initial-setup.sql
        read_only: true
      #- ${HOME:?unset or empty in the .env file}/.docker/volumes/${SQLSERVER_NAME:?unset or empty in the .env file}-data:/var/opt/mssql
      - type: volume
        source: ${SQLSERVER_NAME:?unset or empty in the .env file}-data
        target: /var/opt/mssql
    networks:
      - moname
    ports:
      - ${SQLSERVER_PORT:?unset or empty in the .env file}
    command: ${SQLSERVER_COMMAND:?unset or empty in the .env file}
    #healthcheck: # TODO
    restart: ${RESTART_POLICY:?unset or empty in the .env file}
volumes:
  sqlserver-data:
    name: ${SQLSERVER_NAME:?unset or empty in the .env file}-data
    labels:
      spring.jpa.database: SQLSERVER
