<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.kinlhp</groupId>
		<artifactId>moname-build</artifactId>
		<version>${revision}</version>
	</parent>
	<artifactId>moname-dependencies</artifactId>
	<packaging>pom</packaging>
	<name>${project.artifactId}</name>
	<description>Project to money me with no name [dependencies].</description>
	<properties>
		<main.basedir>${basedir}/..</main.basedir>
		<!-- dependency versions -->
		<!-- # third party # -->
		<assertj-db.version>3.0.0</assertj-db.version>
		<expressly.version>6.0.0-M1</expressly.version>
		<groovy.version>3.0.24</groovy.version>
		<jackson-databind-nullable.version>0.2.6</jackson-databind-nullable.version>
		<liquibase.version>4.31.1</liquibase.version><!-- Keep the same as org.springframework.boot:spring-boot-dependencies#lombok.version -->
		<spring-boot.version>3.5.12</spring-boot.version>
		<swagger.version>2.2.31</swagger.version>
		<testcontainers-keycloak.version>3.7.0</testcontainers-keycloak.version>
		<ulid.version>5.2.3</ulid.version>
	</properties>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.kinlhp</groupId>
				<artifactId>moname-addressing-domain</artifactId>
				<version>${revision}</version>
				<optional>true</optional>
			</dependency>
			<dependency>
				<groupId>com.kinlhp</groupId>
				<artifactId>moname-addressing-jpa</artifactId>
				<version>${revision}</version>
				<optional>true</optional>
			</dependency>
			<dependency>
				<groupId>com.kinlhp</groupId>
				<artifactId>moname-commons-annotation</artifactId>
				<version>${revision}</version>
				<optional>true</optional>
			</dependency>
			<dependency>
				<groupId>com.kinlhp</groupId>
				<artifactId>moname-commons-api</artifactId>
				<version>${revision}</version>
				<optional>true</optional>
			</dependency>
			<dependency>
				<groupId>com.kinlhp</groupId>
				<artifactId>moname-commons-domain</artifactId>
				<version>${revision}</version>
				<optional>true</optional>
			</dependency>
			<dependency>
				<groupId>com.kinlhp</groupId>
				<artifactId>moname-commons-jpa</artifactId>
				<version>${revision}</version>
				<optional>true</optional>
			</dependency>
			<dependency>
				<groupId>com.kinlhp</groupId>
				<artifactId>moname-commons-stream</artifactId>
				<version>${revision}</version>
				<optional>true</optional>
			</dependency>
			<!-- # third party # -->
			<!-- mapstruct -->
			<dependency>
				<groupId>org.mapstruct</groupId>
				<artifactId>mapstruct</artifactId>
				<version>${mapstruct.version}</version>
				<optional>true</optional>
			</dependency>
			<!-- openapitools -->
			<dependency>
				<groupId>org.openapitools</groupId>
				<artifactId>jackson-databind-nullable</artifactId>
				<version>${jackson-databind-nullable.version}</version>
				<optional>true</optional>
			</dependency>
			<!-- springframework -->
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>${spring-boot.version}</version>
				<type>pom</type>
				<scope>import</scope>
				<optional>true</optional>
			</dependency>
			<!-- swagger -->
			<dependency>
				<groupId>io.swagger.core.v3</groupId>
				<artifactId>swagger-annotations</artifactId>
				<version>${swagger.version}</version>
				<optional>true</optional>
			</dependency>
			<dependency>
				<groupId>io.swagger.core.v3</groupId>
				<artifactId>swagger-models</artifactId>
				<version>${swagger.version}</version>
				<optional>true</optional>
			</dependency>
			<!-- ulid -->
			<dependency>
				<groupId>com.github.f4b6a3</groupId>
				<artifactId>ulid-creator</artifactId>
				<version>${ulid.version}</version>
				<optional>true</optional>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<profiles>
		<profile>
			<id>test</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<build>
				<pluginManagement>
					<plugins>
						<!-- # third party # -->
						<!-- gmavenplus -->
						<plugin>
							<groupId>org.codehaus.gmavenplus</groupId>
							<artifactId>gmavenplus-plugin</artifactId>
							<dependencies>
								<!-- # third party # -->
								<!-- groovy -->
								<dependency>
									<groupId>org.codehaus.groovy</groupId>
									<artifactId>groovy-all</artifactId>
									<version>${groovy.version}</version>
									<type>pom</type>
									<scope>runtime</scope>
									<optional>true</optional>
								</dependency>
							</dependencies>
						</plugin>
					</plugins>
				</pluginManagement>
			</build>
			<dependencyManagement>
				<dependencies>
					<dependency>
						<groupId>com.kinlhp</groupId>
						<artifactId>moname-commons-test</artifactId>
						<version>${revision}</version>
						<optional>true</optional>
					</dependency>
					<!-- # third party # -->
					<!-- assertj -->
					<dependency>
						<groupId>org.assertj</groupId>
						<artifactId>assertj-db</artifactId>
						<version>${assertj-db.version}</version>
						<optional>true</optional>
					</dependency>
					<!-- glassfish -->
					<dependency>
						<groupId>org.glassfish.expressly</groupId>
						<artifactId>expressly</artifactId>
						<version>${expressly.version}</version>
						<optional>true</optional>
					</dependency>
					<!-- testcontainers -->
					<dependency>
						<groupId>com.github.dasniko</groupId>
						<artifactId>testcontainers-keycloak</artifactId>
						<version>${testcontainers-keycloak.version}</version>
						<optional>true</optional>
						<exclusions>
							<exclusion>
								<groupId>org.testcontainers</groupId>
								<artifactId>testcontainers</artifactId>
							</exclusion>
						</exclusions>
					</dependency>
				</dependencies>
			</dependencyManagement>
		</profile>
	</profiles>
</project>
