# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
# README#spring-boot
# README#spring-security
server:
  ssl:
    bundle: ed25519-p12
    client-auth: WANT
    enabled-protocols: TLSv1.3
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${application.spring.security.oauth2.resourceserver.jwt.issuer-uri.scheme:http}://\
            ${application.spring.security.oauth2.resourceserver.jwt.issuer-uri.authority.host:localhost}:\
            ${application.spring.security.oauth2.resourceserver.jwt.issuer-uri.authority.port:${random.int[1024,49151]}}\
            ${application.spring.security.oauth2.resourceserver.jwt.issuer-uri.relative-path:/auth}\
            /realms/moname"
      client:
        provider:
          keycloak:
            token-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/token
  ssl:
    bundle:
      jks:
        # org.springframework.boot.autoconfigure.ssl.JksSslBundleProperties
        ed25519-p12:
          key:
            alias: keycloak
            password: moname
          keystore:
            location: classpath:oidc/keycloak/tls/keystore.ed25519.p12
            password: moname
            #provider:
            type: PKCS12
          #options:
            #ciphers:
            #enabled-protocols:
          protocol: TLS
          reload-on-update: true
          truststore:
            location: classpath:oidc/keycloak/tls/truststore.ed25519.p12
            password: moname
            #provider:
            type: PKCS12
        rsa-p12:
          key:
            alias: keycloak
            password: moname
          keystore:
            location: classpath:oidc/keycloak/tls/keystore.rsa.p12
            password: moname
            #provider:
            type: PKCS12
          #options:
            #ciphers:
            #enabled-protocols:
          protocol: TLS
          reload-on-update: true
          truststore:
            location: classpath:oidc/keycloak/tls/truststore.rsa.p12
            password: moname
            #provider:
            type: PKCS12
      pem:
        # org.springframework.boot.autoconfigure.ssl.PemSslBundleProperties
        ed25519-pem:
          key:
            alias: keycloak
            password: moname
          keystore:
            certificate: classpath:oidc/keycloak/tls/certificate.ed25519.pem
            private-key: classpath:oidc/keycloak/tls/private-key.ed25519.pem
            private-key-password: moname
            type: PKCS12
            #verifyKeys:
          #options:
            #ciphers:
            #enabled-protocols:
          protocol: TLS
          reload-on-update: true
          truststore:
            certificate: classpath:oidc/keycloak/tls/certificate.ed25519.pem
            private-key: classpath:oidc/keycloak/tls/private-key.ed25519.pem
            private-key-password: moname
            type: PKCS12
            #verifyKeys:
        rsa-pem:
          key:
            alias: keycloak
            password: moname
          keystore:
            certificate: classpath:oidc/keycloak/tls/certificate.rsa.pem
            private-key: classpath:oidc/keycloak/tls/private-key.rsa.pem
            private-key-password: moname
            type: PKCS12
            #verifyKeys:
          #options:
            #ciphers:
            #enabled-protocols:
          protocol: TLS
          reload-on-update: true
          truststore:
            certificate: classpath:oidc/keycloak/tls/certificate.rsa.pem
            private-key: classpath:oidc/keycloak/tls/private-key.rsa.pem
            private-key-password: moname
            type: PKCS12
            #verifyKeys:
