package com.kinlhp.moname.commons.jpa.entity.ulid;

public enum Discriminator {

	BYTES_AUTO,
	BYTES_DEFAULT,
	BYTES_HASH,
	BYTES_MONOTONIC,
	BYTES_ULID,
	STRING_AUTO,
	STRING_DEFAULT,
	STRING_HASH,
	STRING_MONOTONIC,
	STRING_ULID,
	ULID_AUTO,
	ULID_DEFAULT,
	ULID_HASH,
	ULID_MONOTONIC,
	ULID_ULID,
	UUID_AUTO,
	UUID_DEFAULT,
	UUID_HASH,
	UUID_MONOTONIC,
	UUID_ULID
}
