# GitHub Actions | Reference | Workflows and actions | Workflow syntax
# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax
#
# GitHub Actions | Reference | Workflows and actions | Reusable workflows
# https://docs.github.com/en/actions/reference/workflows-and-actions/reusable-workflows
#
# https://www.schemastore.org/github-workflow.json
name: build
on:
  workflow_call:
    inputs:
      database-profile:
        required: false
        type: string
        default: hsqldb
      keycloak-profile:
        required: false
        type: string
        default: keycloak-unoptimized
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      security-profile:
        required: false
        type: string
        default: security
      test-profile:
        required: false
        type: string
        default: test
jobs:
  package-lifecycle:
    name: package-lifecycle on ${{ inputs.runs-on }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set-up-jdk
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          architecture: x64
          cache: maven
      - name: package-lifecycle (${{ inputs.test-profile }},${{ inputs.database-profile }},${{ inputs.security-profile }},${{ inputs.keycloak-profile }})
        run: "./mvnw \
          --activate-profiles ${{ inputs.test-profile }},${{ inputs.database-profile }},${{ inputs.security-profile }},${{ inputs.keycloak-profile }} \
          --batch-mode \
          --define skipTests=true \
          --no-transfer-progress \
          --threads 1C \
          --update-snapshots \
          clean package"
  verify-lifecycle:
    name: verify-lifecycle on ${{ inputs.runs-on }}
    needs: package-lifecycle
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set-up-jdk
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          architecture: x64
          cache: maven
      - name: dev-CI parity
        run: echo "127.0.0.1 keycloak" | sudo tee -a /etc/hosts # TODO: Replace with `SAN:DNS:keycloak,DNS:localhost,IP:127.0.0.1` and `container.getHost() + getMappedPort()`
      - name: verify-lifecycle (${{ inputs.test-profile }},${{ inputs.database-profile }},${{ inputs.security-profile }},${{ inputs.keycloak-profile }})
        #run: |
          #KEYCLOAK_PROFILES_GROUP="${{ inputs.keycloak-profile }}"
          #./mvnw \
          #--activate-profiles ${{ inputs.test-profile }},${{ inputs.database-profile }},${{ inputs.security-profile }},${{ inputs.keycloak-profile }} \
          #--batch-mode \
          #--define spring.profiles.active=${{ inputs.test-profile }},${{ inputs.database-profile }},${{ inputs.security-profile }},${KEYCLOAK_PROFILES_GROUP%%-*} \
          #--no-transfer-progress \
          #--threads 1C \
          #--update-snapshots \
          #clean verify
        run: "./mvnw \
          --activate-profiles ${{ inputs.test-profile }},${{ inputs.database-profile }},${{ inputs.security-profile }},${{ inputs.keycloak-profile }} \
          --batch-mode \
          --no-transfer-progress \
          --threads 1C \
          --update-snapshots \
          clean verify"
run-name: ${{ github.actor }} is executing build lifecycle
